import type { AdminRepositorySnapshot, AdminPlace } from "./repository-content.ts";
import type { AdminSession } from "./types.ts";

const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
}[character] ?? character));

const styles = `
:root{color-scheme:light;--navy:#0b2944;--gold:#b68a37;--paper:#f7f3e9;--line:#d9d2c3;--muted:#69747d;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:#eef0ed;color:#17212a}a{color:inherit}.shell{max-width:86rem;margin:auto;padding:1.25rem}.top{background:var(--navy);color:white}.top .shell{display:flex;align-items:center;justify-content:space-between;gap:2rem}.brand{font:700 1.45rem Georgia,serif;text-decoration:none}.session{font-size:.85rem;opacity:.8}.nav{background:white;border-bottom:1px solid var(--line)}.nav .shell{display:flex;gap:.75rem}.nav a{padding:.7rem 1rem;border-radius:.65rem;text-decoration:none}.nav a:hover,.nav a:focus-visible{background:var(--paper)}main{padding-block:1.5rem 3rem}.eyebrow{color:var(--gold);font-weight:800;letter-spacing:.12em;text-transform:uppercase;font-size:.75rem}h1,h2{font-family:Georgia,serif;color:var(--navy)}.grid{display:grid;gap:1rem}.stats{grid-template-columns:repeat(4,minmax(0,1fr))}.card,.panel{background:white;border:1px solid var(--line);border-radius:1rem;padding:1.1rem;box-shadow:0 .4rem 1.3rem rgb(12 37 56/.06)}.stat strong{display:block;font:700 2rem Georgia,serif;color:var(--navy)}.status-list{display:flex;flex-wrap:wrap;gap:.5rem}.chip,.badge{display:inline-flex;padding:.28rem .55rem;border-radius:999px;background:var(--paper);font-size:.78rem}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin:1rem 0}.button{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:.7rem;background:var(--navy);color:white;padding:.72rem 1rem;text-decoration:none;font-weight:700;cursor:pointer}.button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #d4a94c;outline-offset:2px}input,select{width:100%;padding:.72rem;border:1px solid #b9c0c5;border-radius:.65rem;background:white;font:inherit}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:.72rem;border-bottom:1px solid #e5e0d5;vertical-align:top}.table th{font-size:.78rem;color:var(--muted)}.table a{font-weight:700;color:var(--navy)}.form{max-width:44rem}.field{display:grid;gap:.35rem;margin-bottom:1rem}.help{font-size:.83rem;color:var(--muted)}.error{color:#8c2020}.success{border-color:#89a784;background:#f5fbf3}.facts{grid-template-columns:repeat(2,minmax(0,1fr))}.facts dt{font-size:.78rem;color:var(--muted)}.facts dd{margin:.2rem 0 0;font-weight:650}@media(max-width:48rem){.stats,.facts{grid-template-columns:1fr 1fr}.table-wrap{overflow-x:auto}.top .shell{align-items:flex-start;flex-direction:column;gap:.5rem}.nav .shell{overflow-x:auto}.shell{padding-inline:1rem}}@media(max-width:30rem){.stats,.facts{grid-template-columns:1fr}}
`;

function layout(title: string, session: AdminSession, body: string, script = ""): Response {
  const identity = session.email ?? session.subject;
  return new Response(`<!doctype html><html lang="sr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex,nofollow"><title>${escapeHtml(title)} — Светиње администрација</title><style>${styles}</style></head><body><header class="top"><div class="shell"><a class="brand" href="/">Светиње · администрација</a><span class="session">Пријављен: ${escapeHtml(identity)}</span></div></header><nav class="nav" aria-label="Главна навигација"><div class="shell"><a href="/">Преглед</a><a href="/places">Објекти</a><a href="/places/new">Нови објекат</a></div></nav><main class="shell">${body}</main>${script ? `<script>${script}</script>` : ""}</body></html>`, { headers: {
    "content-type": "text/html; charset=utf-8",
    "cache-control": "no-store",
    "content-security-policy": "default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'",
    "permissions-policy": "camera=(), microphone=(), geolocation=()",
    "referrer-policy": "no-referrer",
    "x-content-type-options": "nosniff",
    "x-frame-options": "DENY",
  } });
}

export function dashboardPage(session: AdminSession, snapshot: AdminRepositorySnapshot): Response {
  const status = Object.entries(snapshot.stats.statuses).map(([name, count]) => `<span class="chip">${escapeHtml(name)} · ${count}</span>`).join("");
  return layout("Преглед", session, `<p class="eyebrow">Приватни уређивачки простор</p><h1>Преглед</h1><section class="grid stats" aria-label="Статистика"><article class="card stat"><strong>${snapshot.stats.total}</strong>свих објеката</article><article class="card stat"><strong>${snapshot.stats.preview}</strong>у радном приказу</article><article class="card stat"><strong>${snapshot.stats.withCoordinates}</strong>са координатама</article><article class="card stat"><strong>${snapshot.stats.withoutCoordinates}</strong>без координата</article></section><section class="panel"><h2>Уређивачки статуси</h2><div class="status-list">${status}</div><p class="help">Извор: Git грана <code>${escapeHtml(snapshot.branch)}</code>, HEAD <code>${escapeHtml(snapshot.state.headSha)}</code>.</p></section>`);
}

export function placesPage(session: AdminSession, snapshot: AdminRepositorySnapshot): Response {
  const rows = snapshot.places.map((place) => `<tr data-place-row data-search="${escapeHtml(`${place.preferredName} ${place.id}`.toLowerCase())}"><td><a href="/places/${encodeURIComponent(place.id)}">${escapeHtml(place.preferredName)}</a><br><span class="help">${escapeHtml(place.id)}</span></td><td>${escapeHtml(place.placeType ?? "—")}</td><td>${escapeHtml(place.editorialStatus)}</td><td>${escapeHtml(place.browseAreaId ?? "—")}</td><td>${place.latitude !== undefined ? "Да" : "Не"}</td><td>${place.inPreview ? "Да" : "Не"}</td></tr>`).join("");
  return layout("Објекти", session, `<div class="toolbar"><div><p class="eyebrow">Git садржај</p><h1>Објекти</h1></div><a class="button" href="/places/new">Нови објекат</a></div><label class="field">Претрага по називу или ID-ју<input type="search" data-place-search autocomplete="off"></label><div class="panel table-wrap"><table class="table"><thead><tr><th>Назив / ID</th><th>Врста</th><th>Статус</th><th>Област</th><th>Координате</th><th>Preview</th></tr></thead><tbody>${rows}</tbody></table></div>`, `const q=document.querySelector('[data-place-search]');q?.addEventListener('input',()=>{const v=q.value.trim().toLocaleLowerCase('sr');document.querySelectorAll('[data-place-row]').forEach(r=>{r.hidden=!r.dataset.search.includes(v)})});`);
}

export function placePage(session: AdminSession, place: AdminPlace): Response {
  const coordinate = place.latitude !== undefined ? `${place.latitude}, ${place.longitude}` : "Нема";
  return layout(place.preferredName, session, `<p class="eyebrow">Објекат · само читање</p><h1>${escapeHtml(place.preferredName)}</h1><dl class="grid facts panel"><div><dt>Технички ID</dt><dd>${escapeHtml(place.id)}</dd></div><div><dt>Slug</dt><dd>${escapeHtml(place.slug ?? "—")}</dd></div><div><dt>Врста</dt><dd>${escapeHtml(place.placeType ?? "—")}</dd></div><div><dt>Статус</dt><dd>${escapeHtml(place.editorialStatus)}</dd></div><div><dt>Општина</dt><dd>${escapeHtml(place.municipality ?? "—")}</dd></div><div><dt>Насеље</dt><dd>${escapeHtml(place.settlement ?? "—")}</dd></div><div><dt>Координате</dt><dd>${escapeHtml(coordinate)}</dd></div><div><dt>Радни приказ</dt><dd>${place.inPreview ? "Да" : "Не"}</dd></div><div><dt>Извори</dt><dd>${place.sourcesCount}</dd></div><div><dt>Медији</dt><dd>${place.mediaCount}</dd></div></dl>${place.summary ? `<section class="panel"><h2>Сажетак</h2><p>${escapeHtml(place.summary)}</p></section>` : ""}<p><a href="/places">← Назад на објекте</a></p>`);
}

export function newPlacePage(session: AdminSession, supportedPlaceTypes: string[], headSha: string): Response {
  const options = supportedPlaceTypes.map((type) => `<option value="${escapeHtml(type)}">${escapeHtml(type)}</option>`).join("");
  return layout("Нови објекат", session, `<p class="eyebrow">Research scaffold</p><h1>Нови објекат</h1><p class="help">Чување прави два research фајла у једном Git commit-у. Не додаје запис у јавни или editorial-preview приказ.</p><form class="panel form" data-create-form><label class="field">Српски назив<input name="preferredName" required autocomplete="off"></label><label class="field">Технички ID<input name="id" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxlength="100"></label><label class="field">Slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxlength="80"></label><label class="field">Врста<select name="placeType" required>${options}</select></label><input type="hidden" name="expectedHeadSha" value="${escapeHtml(headSha)}"><button class="button" type="submit">Сачувај research запис</button><p data-form-status role="status"></p></form>`, `const f=document.querySelector('[data-create-form]'),s=document.querySelector('[data-form-status]'),n=f.elements.preferredName,i=f.elements.id,g=f.elements.slug,m={'а':'a','б':'b','в':'v','г':'g','д':'d','ђ':'dj','е':'e','ж':'z','з':'z','и':'i','ј':'j','к':'k','л':'l','љ':'lj','м':'m','н':'n','њ':'nj','о':'o','п':'p','р':'r','с':'s','т':'t','ћ':'c','у':'u','ф':'f','х':'h','ц':'c','ч':'c','џ':'dz','ш':'s'};const slugify=v=>[...v.toLowerCase()].map(c=>m[c]??c).join('').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let edited=false;i.addEventListener('input',()=>edited=true);n.addEventListener('input',()=>{if(!edited){const v=slugify(n.value);i.value=v;g.value=v}});f.addEventListener('submit',async e=>{e.preventDefault();s.textContent='Чување…';const body=Object.fromEntries(new FormData(f));const r=await fetch('/api/places',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok){s.className='error';s.textContent=data.error?.message??'Грешка';return}s.className='panel success';s.innerHTML='Сачувано као research. Commit: <code>'+data.commitSha+'</code>. <a href="/places/'+encodeURIComponent(data.place.id)+'">Отвори објекат</a> · <a href="/places">Сви објекти</a>'});`);
}
